<?php
/**
 * ./app/design/frontend/default/default/template/checkout/cart/topbar.phtml
 *
 * based on ./app/design/frontend/base/default/template/checkout/cart/sidebar.phtml
 */
?>
<div class="cart-header">
<div class="block block-cart">
    <?php $_cartQty = $this->getSummaryCount() ?>
    <div class="block-title">
        <a  class="btn_checkout" href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><strong><?php echo $this->__('Checkout »') ?></strong></span></a>
    </div>
    <div class="block-content">
    <?php if ($_cartQty > 0): ?>
        <div class="summary">
            <p class="subtotal">
			<span class="header_cart_price" id="cart_information_span2"><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></span>
                <a class="item_lnk" href="<?php echo $this->getUrl('checkout/cart'); ?>"><strong> <span class="cart_information_span1">
                <?php echo $_cartQty . ' '; ?>
                <?php if ($_cartQty == 1): ?>
                    <?php //echo $this->__('Item') ?>
                <?php else: ?>
                    <?php //echo $this->__('Items') ?>
                <?php endif ?>
                </span></strong></a>
            </p>
            <!--<p class="amount">
                <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('To Cart') ?></a> | 
                <a href="<?php echo $this->getUrl('checkout'); ?>"><?php echo $this->__('Checkout') ?></a>
            </p>-->
        </div>
    <?php else: ?>
        <p class="empty"><span class="header_cart_price" id="cart_information_span2">£0</span><a class="item_lnk" href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php //echo $_cartQty . ' '; ?><strong> <span class="cart_information_span1">0</span></strong></a>
    <?php endif ?>
    </div>
</div>
</div>