<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/productslider.css');?>" media="all" />
<script type="text/javascript" src="<?php echo $this->getJsUrl('magebuzz/jquery/jquery-latest.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('magebuzz/jquery/jquery.bxSlider.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/productslider/simple-slider.css');?>" media="all" />
		<script type="text/javascript">
		   var $simpleSlider = jQuery.noConflict();	
			  $simpleSlider(document).ready(function(){
				$simpleSlider('#list-items').bxSlider({
				  auto: true,
				  autoControls: true
				});
			  });
		</script>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid" id="list-items">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
				<div class="panel-wrapper">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" width="" height="auto" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
					<div class="rate_strip">
						<span> £ </span>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
						<?php endif; ?>
						
						
					</div>
				</div>
			</li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    
</div>
<?php endif; ?>
